### ISSUE TITLE
Cannot pull in Drone 0.7

### ISSUE THREAD

**Issue by ThePixelBro22** [NYTimes/drone-gke#51]
When drone tries to pull the image it gets 

```Drone GKE Plugin built from 7ec003b4df98d5b4160964b2f5ad6a8e75aa553c
panic: EOF
goroutine 1 [running]:
github.com/NYTimes/drone-gke/vendor/github.com/drone/drone-plugin-go/plugin.MustParse()

        /go/src/github.com/NYTimes/drone-gke/vendor/github.com/drone/drone-plugin-go/plugin/param.go:129 +0x4e
main.wrapMain(0x0, 0x0)
       /go/src/github.com/NYTimes/drone-gke/main.go:76 +0x5a3
main.main()
	/go/src/github.com/NYTimes/drone-gke/main.go:50 +0x22```

**Comment by jrynyt** [comment]
that looks like bad parameters passed in through the drone config: https://github.com/drone/drone-plugin-go/blob/master/plugin/param.go#L124-L130

unrelated to pulling image.

**Comment by ThePixelBro22** [comment]
@jrynyt  ok, makes sense. I removed to the secrets just to test if that would run. But when have the secrets i get this error 
`ERROR: yaml: unmarshal errors: line 23: cannot unmarshal !!map into []*yaml.Secret`

**Comment by ThePixelBro22** [comment]
Looks like I had the secrets collum when i didn't need it.
