### ISSUE TITLE
Ability to deploy an existing kube.yml file

### ISSUE THREAD

**Issue by ThePixelBro22** [NYTimes/drone-gke#52]
Is it possible with this plugin to just put the bare minimum parameters to deploy a deployment.yml like file?

```gke:
    image: nytimes/drone-gke

    zone: us-central1-a
    cluster: my-k8s-cluster
    namespace: $$BRANCH
    token: >
      $$GOOGLE_CREDENTIALS
```

We can use this to just log onto GKE and let it deploy the kube.yml without requiring all the vars and secret to put into the kube.yml file

**Comment by jrynyt** [comment]
have you tried it?

according to https://github.com/NYTimes/drone-gke/blob/master/main.go#L226-L230, the secret template is optional.

If you want it to use another kube yaml file besides `/.kube.yml`, use `template` (see https://github.com/NYTimes/drone-gke/blob/master/DOCS.md)

**Comment by ThePixelBro22** [comment]
@jrynyt  I have tried it and i get this error

```Drone GKE Plugin built from 7ec003b4df98d5b4160964b2f5ad6a8e75aa553c

panic: EOF
goroutine 1 [running]:
github.com/NYTimes/drone-gke/vendor/github.com/drone/drone-plugin-go/plugin.MustParse()
	/go/src/github.com/NYTimes/drone-gke/vendor/github.com/drone/drone-plugin-go/plugin/param.go:129 +0x4e
main.wrapMain(0x0, 0x0)
	/go/src/github.com/NYTimes/drone-gke/main.go:76 +0x5a3
main.main()
	/go/src/github.com/NYTimes/drone-gke/main.go:50 +0x22
```
and this is my dorne.yml

```pipeline:
  deploy:
    image: nytimes/drone-gke
    zone: us-central1-a
    cluster: joule-dev
    namespace: dev
    token: >
        {
      <token>
        }
```

**Comment by jrynyt** [comment]
that is the same parameter parsing error from your other issue. It probably has to do with the indentation of the token value -- all lines need the exact same whitespace to the left.

BUT...you should not be putting your GCP credentials in the clear like that -- that's what secrets are for.

**Comment by ThePixelBro22** [comment]
ok i updated it to 

``` 
 deploy:
      image: nytimes/drone-gke
      zone: us-central1-a
      cluster: joule-dev
      namespace: dev
      secret: google_token
```
and get the same error, but i am use the same token for my gcr building and pushing and it works fine.

**Comment by jrynyt** [comment]
what version of drone are you running?

**Comment by ThePixelBro22** [comment]
@jrynyt  0.7

**Comment by jrynyt** [comment]
You're using a version of the plugin that only works with 0.4.

I see an updated version was [merged](https://github.com/NYTimes/drone-gke/pull/33) to the develop branch months ago, but it is still not in master. @tonglil and/or @stephansnyt should be able to give you more info, since it's not clear to me what the status is.

However I'm guessing you could try using [`nytimes/drone-gke:develop`](https://hub.docker.com/r/nytimes/drone-gke/tags/) as your plugin image.

**Comment by ThePixelBro22** [comment]
ok ill try that and report back, Thank you so much for helping people out like me.

**Comment by ThePixelBro22** [comment]
So now it gives me a nice error,

`Missing required param: token`

but I see that I clearly have the token.

**Comment by ThePixelBro22** [comment]
Hmm seems like im getting a param error
`Missing required param: token`

but I clearly see the token.

**Comment by ThePixelBro22** [comment]
Well looks like i got it by doing this 

```
    secrets:
      - source: google_token
        target: token
```

thank you for your help @jrynyt!!!!
