### ISSUE TITLE
After gke does the kubectl apply does it reset the service automatically?

### ISSUE THREAD

**Issue by ThePixelBro22** [NYTimes/drone-gke#53]
title

**Comment by jrynyt** [comment]
what does "reset the service" mean?

**Comment by ThePixelBro22** [comment]
@jrynyt  If there is a previous deployment already running on the cluster,  does it run the new software.

**Comment by jrynyt** [comment]
All this plugin does is run `kubectl apply` on your .kube.yml. So yes, if you change the image name/tag on an existing deployment, it will swap in the new containers.
