### ISSUE TITLE
Pods do not update with push

### ISSUE THREAD

**Issue by ThePixelBro22** [NYTimes/drone-gke#55]
When drone says the kubectl has been applied it seems my pods stay the same and never update.

**Comment by jrynyt** [comment]
I'm happy to help, but you need to provide detailed information. Based on the issues you've opened so far, it seems like you are missing basic knowledge of kubernetes. Have you read the kubernetes documentation?

**Comment by ThePixelBro22** [comment]
I do admit that I am a beginner with kubernetes and ready most of the documentation, but also lack experience to articulate what's actually happening.  I meant to say does the plug in preform rolling updates. Deploying new software without any down time.

**Comment by jrynyt** [comment]
All the plugin does is run `kubectl apply -f .kube.yml,.kube.sec.yml`. Yes, that does a rolling update if you've updated a Deployment.

Please read the kubernetes documentation, and if you feel like something is wrong with this plugin, open an issue with the relevant configuration and logs.
