### ISSUE TITLE
Update "wait" fields

### ISSUE THREAD

**Issue by tonglil** [nytimes/drone-gke#99]
**Is your feature request related to a problem?**
Plugin is only capable of "waiting" on _Deployment_ workloads.

The current `wait_deployments` fields is hard coded to running `kubectl rollout status` for _Deployments_ only (https://github.com/NYTimes/drone-gke/blob/57c5e00070efb62240c37b5f5d6d22c5878a3ddf/main.go#L628).

The `rollout` command is capable of checking the status for multiple workload types (https://github.com/kubernetes/kubernetes/blob/426ef9d349bb3a277c3e8826fb772b6bdb008382/pkg/kubectl/cmd/rollout/rollout_status.go#L95).

**Describe the solution you'd like**
- Create a wait `wait` field:

```
wait:
  - deployment/xyz
  - statefulset/abc
  - ds/my-daemon-set
```

- Deprecate the `wait_deployments` field (with a warning message in the logs).
- Remove the `wait_deployments` field in a future version bump.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bennettyates** [comment]
We discussed this issue in [PR 124](https://github.com/nytimes/drone-gke/pull/124) and it was recommended we do not introduce a new option and instead just generalized the existing `wait-deployments` to handle additional types.  That approach was taken in [PR 125](https://github.com/nytimes/drone-gke/pull/125).
